name: life_english
description: A Flutter application study Life English.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.18.0
  http: ^0.12.0+1
  # Dependency injection
  inject:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject
      ref: 7c3cbf6

dependency_overrides:
  analyzer: ^0.39.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.0
  inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator
      ref: 7c3cbf6

  mockito: ^4.1.0

flutter:
  uses-material-design: true
